language: node_js
node_js:
  - lts/*
before_script:
  - chmod +x ./scripts/proto-install.sh && ./scripts/proto-install.sh
script:
  - chmod +x ./scripts/build-js.sh && ./scripts/build-js.sh
deploy:
  - provider: scrip
    skip_cleanup: true
    script: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh
    on:
      branch: main