language: node_js
node_js:
  - lts/*
before_script:
  - npm install -g pbjs
script:
  - pbjs proto/ProtoWsHeader.proto --ts ts/proto-ws-structs.d.ts --es6 js/proto-ws-structs.js
  - chmod +x ./scripts/version.sh && ./scripts/version.sh
deploy:
  - provider: scrip
    skip_cleanup: true
    script: chmod +x ./scripts/deploy-js-ts.sh && ./scripts/deploy-js-ts.sh
    on:
      branch: main