language: node_js
node_js:
  - lts/*
before_script:
  - PROTOC_ZIP=protoc-3.14.0.-linux-x86_64.zip
  - curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
  - unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
  - unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
  - rm -f $PROTOC_ZIP
script:
  - chmod +x ./scripts/build-js.sh && ./scripts/build-js.sh
deploy:
  - provider: scrip
    skip_cleanup: true
    script: chmod +x ./scripts/deploy.sh && ./scripts/deploy.sh
    on:
      branch: main