language: node_js
node_js:
  - lts/*
before_script:
  - npm install -g pbjs
script:
  - pbjs proto/ProtoWsHeader.proto --ts ts/proto-ws-structs.d.ts --es6 js/proto-ws-structs.js
  - ls -la ts
  - ls -la js