language: node_js
node_js:
  - lts/*
before_script:
  - npm install -g pbjs
script:
  - pbjs proto/ProtoWsHeader.proto --ts ts/proto-ws-structs.d.ts --es6 js/proto-ws-structs.js
  - ls -la ts
  - ls -la js
deploy:
  - provider: scrip
    script: js/build.sh
    on:
      branch: main
  - provider: script
    script: ts/build.sh
    on:
      branch: main